name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0

      - name: Install dependencies
        run: |
          make setup
      
      - name: Test with pytest
        run: |
          make test